### ISSUE TITLE
[Emacs24.3][Mac] フルスクリーン時に画面上部に何も表示されない

### ISSUE THREAD

**Issue by ttanimichi** [emacs-jp/issues#11]
既出の問題だったらすいません。

Emacs24.3からMacのフルスクリーンに対応したようですが、
実際にフルスクリーンにしてみると画面上部に何も表示されない領域ができてしまい、
画面をフルに利用できないようです。
[この画像](https://www.dropbox.com/s/m2jqnkczynhswia/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202014-01-13%2016.33.48.png) の場合だと、/Users/tkr/emacs.d:の上部が真っ黒になり
何も表示されないようです。

何か回避策などありましたら教えて下さい。

**Comment by syohex** [comment]
試せていませんが, すぐに見つかったものを貼っておきます.

http://tech.kazeor.net/blog/2013/05/03/better-full-scrren-mode-on-cocoa-emacs-24-dot-3/

Emacswikiによると 24.4から fullscreenにいろいろ対応しているようですが,
こちらも今のところ未確認です.

http://www.emacswiki.org/emacs/FullScreen#toc23

**Comment by ironsand** [comment]
24.3 のバグなので、自分の環境では git のHEAD から `brew install emacs --cocoa --use-git-head --HEAD` で 24.3.50をインストールすれば解決しました。

ただ、そうすると今度は起動時に`ad-Advice-package--add-to-archive-contents: Symbol's function definition is void: package-desc-vers` のエラーが出るようになり package manager が使えない状態です。

**Comment by syohex** [comment]
> ただ、そうすると今度は起動時
> にad-Advice-package--add-to-archive-contents: Symbol's function definition is void: package-desc-vers のエラーが出るようになり package manager が使えない状態です。

数ヶ月前これに関する問題がいくつか報告されていますが, 新し目のものだと関数として
見えているので大丈夫なのではないでしょうか ? 私は今月の初めぐらいのソースを使って
いますが, package.elは問題なく使えています.

https://github.com/cask/cask/issues/69
https://github.com/purcell/emacs.d/issues/110

**Comment by ironsand** [comment]
最新だと修正されているんですね。ご指摘ありがとうございます。

**Comment by ttanimichi** [comment]
助かりました。ご回答ありがとうございました。
