### ISSUE TITLE
[ELPA] Githubで.emacs.dを管理する場合のベストプラクティス

### ISSUE THREAD

**Issue by ttanimichi** [emacs-jp/issues#12]
ググってもあまり良い方法が見つからなかったので質問させて頂きます。

package.elを主に使用してプラグインを管理して、Githubにpush / pull することで
複数台のマシンで.emacs.dを同期する場合、どうするのが最も良い方法なのでしょうか？

僕の場合、.elcを.gitignoreで除外して、 ~/.emacs.d /elpa/ ディレクトリも含めてGithubにpushしているのですが( https://github.com/tanimichi/dot.emacs.d ) 
この方法ではpullしたマシンですべてのelispをバイトコンパイルし直すことになります。
すべてのelispファイルをバイトコンパイルするスクリプトを書けばこの方法でも
まあ良いのかなとも思うのですが、
- .emacs.d /elpa/ 下にはバイトコンパイルできないelispファイルも含まれている ( *-autoloads.el )
- ELPAの使用方法として、本来であれば常にELPA経由でDLすべきであろうelispファイルをGithubからpullして取得している点が美しくない

といった問題があるように思えます。

何か良い方法があれば教えて下さい。

**Comment by masutaka** [comment]
私の場合、.elcも含めて~/.emacs.d/elpaにcommitしています。
packageをアップデートして不具合があった時に、何も考えずにrevertすれば良いのが楽です。
美しくはないかもしれませんねw

ちなみに~/.emacs.dを含めたdot filesの管理は、以下のようにしています。
HOME直下でGit管理したいものを https://github.com/masutaka/home (private repository) としてPush。
~/project/homeにcloneしてきて、HOMEからシンボリックリンクを張る。
手動で張るのはやめてBoxenとかPuppetで管理しようかなとは思っています。

**Comment by gongo** [comment]
私は package.el や el-get でインストールしたいパッケージ名だけを commit しています(あとはそれらの設定ファイル等)。

https://github.com/gongo/elfactory

使いたい時は
1. `git pull` (初めての時は `git clone`)
2. `make init`
   - `~/.emacs.d` 内にシンボリックリンクを貼ったり等するタスク
3. `make install-elisp`
   - インストールパッケージ一覧をみて `package-install` や `el-get-install` してくれるタスク
   - https://github.com/gongo/elfactory/blob/master/packages/elpa.el
   - https://github.com/gongo/elfactory/blob/master/packages/el-get.el

みたいな流れでセットアップするようにしています。
最初は `~/.emacs.d/{elpa,el-get}` をまるごと push しようと思っていたのですが
とりあえず今の形に落ち着きました。

**Comment by syohex** [comment]
パッケージを同じものだけ使うというのであれば, [Cask](http://cask.github.io/)を使うのが良いのでは,
ないでしょうか ? それで `Cask`ファイルだけ githubに入れておけば, 同じもののセットアップができる
と思います. (対象とするパッケージがちゃんとタグが付けられている必要があると思いますが).

パッケージ以外のものについては(bookmark情報等)については, リポジトリに含ませざるを
得ないと思います.

**Comment by ttanimichi** [comment]
皆様ご回答ありがとうございます。大変参考になります。

この件ですが、ELPAがそもそもGithub（のようなgitリモートリポジトリ）でpush / pullして同期することを前提に設計されていないことが煩雑さを生んでいるように思えます。Emacsの設定もすべてクラウドで管理して、Emacsをもっとポータブルな環境にしたいですね。

本件とは直接関係ないですが、~/.emacs.d/ 以下のディレクトリ階層のベストプラクティスも、個人的にはEmacsとして用意してあったほうが良いのになと思います。（例えば、Ruby on Railsにおけるrails newコマンドのように、タスクを走らせるとディレクトリと雛形となるファイルが自動生成されるようにする、とか。そういえばEmacs用のビルドツールってあまり聞かないですね。makeとかRakeが使われている場合が多いのかな？RailsにおけるRakeのように、標準で使用できるビルドツールがEmacsにも標準添付されていると、elファイルの再帰的なバイトコンパイルのような決まりきった作業をタスクとして用意しやすくなるように思えるのですが、どうなんでしょう。 <- syohex さんに教えていただいたCaskがもっと普及するとそういったこともできるようになるのかもしれませんね）。

設定より規約（Convention over Configuration）的な考え方を設計に取り入れていないがゆえに、ただでさえ険しいEmacsの学習曲線が、より険しくなっているように思えます。自由にカスタマイズできることはEmacsにとって非常に重要なことだと思いますが、ある程度の規約を設けることで設定の手間を省くことができるんじゃないかなぁと。プラグインに関しても、helm, auto-complete, yasnippet, elpaのような、おそらくは多くのユーザが使用しているであろうプラグインに関しては標準添付するだけではなくデフォである程度の設定があらかじめ用意されていて、それをいじることで手軽にカスタマイズできるようにする、とか。あまりにも学習曲線が険しすぎると若い人はSublimeに移ってしまうし、規約を設けることで設定の手間を省くことができるんじゃないかなぁと。

Githubへのpull / pushによる同期に関しても、.emacs.d以下のディレクトリ階層に関しても、ユーザがそれぞれ独自の方法を考えて車輪の再発明のようなことをしている様子がStrutsで開発していた頃のJavaプロジェクトみたいでレガシーな感じがします。Railsのようにある程度の規約があればもっと今風な感じにできるんじゃないかなと思うんですが、上手い方法が何かないかなぁと。

**Comment by masutaka** [comment]
便乗で質問させて下さい。
Caskって、Gemfile+Gemfile.lockのように、バージョンも含めて管理できますか？

**Comment by ttanimichi** [comment]
僕のスキルでは無理ですが、
1. EmacsをRuby or mrubyで実装しなおす（Rmax??）
2. rmaxコマンドで~/rmax.d/ 以下のディレクトリ階層と設定ファイルの雛形を自動生成
3. Rubyで設定・拡張できるようにする
4. ビルドツールにはRakeを使う

みたいなことができるとEmacsが一気に今風な感じになって面白いのになぁと思うんですけど… まあ、僕のスキルでは無理なんですけど…

**Comment by syohex** [comment]
@masutaka バージョンは指定できますが, バージョンを固定というのは今のところ無理でした.
試してみたところ指定したバージョン以上のものがインストールされるだけのようです.

**Comment by masutaka** [comment]
@syohex 
ありがとうございます！ 様子見しますw

**Comment by shibayu36** [comment]
caskでversion固定できるようになるとそれを使うのが良さそうに見える

**Comment by Shougo** [comment]
> この件ですが、ELPAがそもそもGithub（のようなgitリモートリポジトリ）でpush / pullして同期することを前提に設計されていないことが煩雑さを生んでいるように思えます。Emacsの設定もすべてクラウドで管理して、Emacsをもっとポータブルな環境にしたいですね。

そもそも、package.elはaptのような存在ですからね。.emacs.elの設定を共有して、どこでも同じプラグインを使う、というような目的には向かないのだと思います。

> ```
> EmacsをRuby or mrubyで実装しなおす（Rmax??）
> ```
> 
>    rmaxコマンドで~/rmax.d/ 以下のディレクトリ階層と設定ファイルの雛形を自動生成
>    Rubyで設定・拡張できるようにする
>    ビルドツールにはRakeを使う

夢があってよいですが、無理だと思います。下手なforkは混乱を生むだけです。

**Comment by shishi** [comment]
EmacsでもVimでも、何でもできるがゆえにデフォルトはコンパクトにまとまっていることと引き換えになっている設定の面倒さ、負担はきっと大昔から多くの人が思っているのになぜ解決されないのでしょうね…
設定自身が楽しいとはいっても、道具を便利にしたい、という目的からはなくてもいいものですものね。

**Comment by Shougo** [comment]
> EmacsでもVimでも、何でもできるがゆえにデフォルトはコンパクトにまとまっていることとと引き換えになっている設定の面倒さ、負担はきっと大昔から多くの人が思っているのになぜ解決されないのでしょうね…

おそらく、機能の増加とユーザーの多様性に無理やり対応した結果がこれなのだと思います。
エディタには色んなユーザーがいて、本来は全てに対応することは不可能です。
ただ、全てに対応する道が唯一存在し、それが「深い部分まで設定を可能にする」ことと「エディタに拡張性を与える」ことです。「簡単に使える」こととは当然矛盾するので、これを解決するのは極めて難しいです。
「簡単に使える」ようにするには機能を削らなければいけないはずで、大きな反発があるでしょう。

**Comment by ttanimichi** [comment]
@Shougo さん

> そもそも、package.elはaptのような存在ですからね。.emacs.elの設定を共有して、どこでも同じプラグインを使う、というような目的には向かないのだと思います。

そうですね。bundler的な存在であればもっとポータブルな環境にできるのになと思ったのですが、そういう用途であれば @syohex さんに教えていただいたCaskが良さそうなので試してみようと思います。

> 夢があってよいですが、無理だと思います。下手なforkは混乱を生むだけです。

それは僕も分かってます笑　実現可能性を無視してちょっと夢想してみただけです。

> エディタには色んなユーザーがいて、本来は全てに対応することは不可能です。ただ、全てに対応する道が唯一存在し、それが「深い部分まで設定を可能にする」ことと「エディタに拡張性を与える」ことです。「簡単に使える」こととは当然矛盾するので、これを解決するのは極めて難しいです。

おそらく @Shougo さんの仰る通りなのでしょうが、例えばプラグインに関して言えば、helm, auto-complete, yasnippet, elpaのように多くのユーザが共通して使用しているであろうものもあるし、骨組みとなる基本的なディレクトリ階層であったり、Githubとの同期する際のベストプラクティスといった、大多数のユーザに共通しているであろう部分もあるんじゃないかなぁと思ったんです。ただ、 @Shougo さんの仰るように「深い部分まで設定を可能にする」ことと「エディタに拡張性を与える」ことが「機能の増加とユーザーの多様性に対応する唯一の道」であったという点には僕も100%同意です。

**Comment by Shougo** [comment]
> そうですね。bundler的な存在であればもっとポータブルな環境にできるのになと思ったのですが、そういう用途であれば @syohex さんに教えていただいたCaskが良さそうなので試してみようと思います。

私はCaskが他とどう違うのかよくわかっていません。誰か紹介記事書いてくれないかな……。

> それは僕も分かってます笑　実現可能性を無視してちょっと夢想してみただけです。

Vim界にもよくそういう話が出るので、ちょっと反応してみました。

> おそらく @Shougo さんの仰る通りなのでしょうが、例えばプラグインに関して言えば、helm, auto-complete, yasnippet, elpaのように多くのユーザが共通して使用しているであろうものもあるし、骨組みとなる基本的なディレクトリ階層であったり、Githubとの同期する際のベストプラクティスといった、大多数のユーザに共通しているであろう部分もあるんじゃないかなぁと思ったんです。

そこが非常に難しいと思うのです。私としては最初から何も考えずプラグインをインストールしまくるのもどうかと思うし、プラグインは各自取捨選択するのが良いと考えています。とはいえ、初心者へのフォローや情報をまとめるためにも、「最初はここを見ておけば大丈夫」という場所は必要でしょう。おそらく、それがemacs-jpのページなのだと思います（ですよね？）。

**Comment by Shougo** [comment]
Caskをちょっと調べてみました。うっ、これはWindowsに対応していないコードだ。
そもそもコマンドラインツールみたいだし。

ここまでWindowsが冷遇されるとは、未だにWindowsでEmacsは修羅の道……。

**Comment by ttanimichi** [comment]
皆様コメントありがとうございました。 @syohex さんに教えていただいたCask を試してみようと思います。
