### ISSUE TITLE
popwin.elとhelmを併用したときre-builderを実行するとフォーカスが外れる

### ISSUE THREAD

**Issue by takanopontaro** [emacs-jp/issues#14]
こんにちは。
どうしても解決しない問題がありまして、お知恵を拝借できないかと…

現象：
popwin.elとhelmを併用したときにre-builderを実行すると、フォーカスがre-builderバッファではなく、元のウィンドウに移ってしまう。
（最初はre-builderバッファにフォーカスがあるが、その後すぐに移る）

環境：
MacOSX 10.9
HomebrewでインストールしたEmacs24.3

設定：
以下の設定になります。MELPAを使っています。他の拡張は全部外して確認しました。
Helm系バッファを常に下に開きたいためこの設定にしています。

``` lisp
(require 'popwin)
(setq display-buffer-function 'popwin:display-buffer)
(setq popwin:close-popup-window-timer-interval 0.5)
(push '("Helm" :regexp t :position bottom :height 0.4) popwin:special-display-config)
(require 'helm-config)
(helm-mode 1)
```

`:regexp t`を外すとこの現象は起きませんでした。

Emacsを使い始めたばかりでまだ知見がないため、とんちんかんな質問になっているかもしれませんが、なにかぴんと来る方がいらっしゃいましたらどうぞよろしくお願いいたします。

**Comment by syohex** [comment]
再現することを確認しました.

`*helm-mode-execute-extended-command*`バッファに条件がマッチしてしまった
ためと考えられます. `re-builder`に限らず, 似たような挙動なものを全部ご指摘の
ような挙動になりました.

追記 `*helm-mode-execute-extended-command*`は明示的に操作しなくても
見えなくなってしまうバッファなので, それに対して `popwin`が適用されるのは
よろしくないと考えられる.

**Comment by syohex** [comment]
`M-x re-builder`だと問題の挙動になりますが, `M-: (re-builder)`だと問題ないようです.

追記 `M-: (re-builder)`だと `*helm-mode-execute-extended-command*`が表示されないため.

**Comment by syohex** [comment]
`*helm-mode-execute-extended-command*`ようなバッファが存在することを考えると,
`Helm`という指定だけで helm全般で popwinを有効にするというのは難しいように
思えます. 現状細かに指定するという方式を取らざるを得ないのではないかと思います.

**Comment by takanopontaro** [comment]
syohexさん

ご返信どうもありがとうございます。なるほど、そういうことでしたか…
`*helm-mode-execute-extended-command*`というものは知りませんでした。

popwin.elのソースを読むと、

> PATTERN is in general a buffer name, a symbol
> specifying major-mode of buffer, or a predicate function which
> takes one argument: the buffer.

とありました。文字列やシンボルの代わりに関数を指定して、その戻り値か何かを利用できるのかなと思ったのですが、このpredicate functionというのが何か分からず…（Lisp初心者です）

調べたかぎり、そのバッファを引数に取りnilかtを返す関数、なのかなと（勝手に）思い、いろいろ試したのですが、うまく行きませんでした。

このpredicate functionについてもし何か知っていらしたらご教授いただけると幸いです。

**Comment by syohex** [comment]
predicate functionはお考えの通り真偽値を返す関数です. Rubyだと `?`で終わっている
関数です. Emacs Lisp(Common Lisp系)だと `nil`以外は全部 `t`なので, `nil`返すかそれ以外を
返す関数と思っていただければよいです. 以下に例を示します.

``` lisp
(defun my/popwin-helm-p (buffer)
  (let ((name (buffer-name buffer)))
    (unless (string= name "*helm-mode-execute-extended-command*")
      (string-match-p "Helm" buffer))))
```

popwinで指定する predicate functionは説明にあるとおり, バッファオブジェクトを引数と
して受け取る 1引数関数として定義する必要があります.  あとはその引数を使って
`nil`かそうでないかを返します(使わなくても構わないですが). この例の場合は,
`buffer-name`オブジェクトから名前を取り出して, それが `*helm-mode-execute-extended-command*`でない場合, `Helm`を含むかを調べています(Rubyなんかと同じく,
最後に評価した値が戻り値になるので, 明示的な returnは基本不要です.)

あとは以下のように関数を指定するだけです.

``` lisp
(push '(my/popwin-helm-p :position bottom :height 0.4) popwin:special-display-config)
```

**Comment by takanopontaro** [comment]
サンプルまで書いていただきありがとうございます！ 想定した動きになりました！
popwinは細かい条件で使い分けたいと考えていて、この手法は便利なので、これで行こうと思います。

同じように書いていたつもりなんですが、自分でいろいろ試していた関数は上手く動きませんでした。
Lisp難しいっす。でもユニークで面白いです ^^

とても勉強になりました。どうもありがとうございました。

※現象の原因が分かったため、Closeさせていただきます
