### ISSUE TITLE
Package-Requires の書式

### ISSUE THREAD

**Issue by lurdan** [emacs-jp/issues#15]
package.el の依存関係指定で、or 的な条件指定ってできたりしないでしょうか。

orgbox が org 8.0 を require してるのですが、org-plus-contrib 使ってるので、そちらでも依存が満たされて欲しいなぁと。

**Comment by syohex** [comment]
OR指定というのは無理なようです.

**Comment by lurdan** [comment]
ですかー、残念です。
どちらかというと、org ELPA で「依存関係で困るから、別名で同じ機能のパッケージ提供するのはやめてー」と働きかけた方がいいかもですね。
