### ISSUE TITLE
便利に使えるコマンド早見表が欲しい

### ISSUE THREAD

**Issue by NaClOaq** [emacs-jp/issues#16]
初めまして、質問させてください。
新規に導入したモードやあやふやなコマンドがあった時`describe-bindings`します。これ自体はリンク集として良好なのですがコマンド名から動作が想起しずらいものもあります。
リファレンスを読んでも当然ながら英語でイマイチぱっとしなかったり。
日本人作者であればwebサイトから日本語のリファレンスを毎度参照したり。
最初からweb検索して紹介記事などを参照したり…
そこから自分で適当なファイルにメモを作成したりするのですがそれもなにかと管理が面倒です。

そこで`describe-bindings`したときのコマンド一覧のやたらと空いている右側に自分の一行メモを残したりタグ付けしたりできると如何にも早見表のようで良いのに、とか。
他にはinit.elや~/.JP.elを作ってそこから`describe-funtion`の個々の参照先に自分のメモ書きや日本語で簡単な要約等を追加したりとかそんなことができれば便利なのになぁと思っております。
私自身はあまりプログラマライクでもなくここで質問するには似合わないかもしれませんがそんな要望を満たしてくれる設定や機能を持った拡張、他にこう言うやり方が便利だ等がありましたら教えてください。
環境：Win7,GNUpackEmacs24.3.1

**Comment by lurdan** [comment]
私自身で使ってるわけではないですが、まさにご希望の機能のように思えます。
http://d.hatena.ne.jp/rubikitch/20070702

**Comment by NaClOaq** [comment]
クリーンヒットありがとうございます。
早速入れてみて`describe-bindings`の*Help*にも書き込めるものかと勘違いして手間取ってしまいました。
`describe-funtion`にはバッチリ書き込めました。
検索しているとeditable-help.elというHelpメモを共有できる拡張まで実現していてビックリです。

しかしやはり`describe-bindings`の方にも書き込めると嬉しいのでもう少し開けさせていただきます。

**Comment by NaClOaq** [comment]
とりあえず必要そうなメモはorgでまとめていこうかと思います。ありがとうございました。
