### ISSUE TITLE
Helmのミニバッファで日本語が入力できない

### ISSUE THREAD

**Issue by takanopontaro** [emacs-jp/issues#17]
こんにちは。
初歩的なことかもしれませんがお知恵を拝借したく質問させていただきます。

現象：
Helmのミニバッファで日本語が入力できない
（ペーストはできます）

環境：
MacOSX 10.9
HomebrewでインストールしたEmacs24.3

検索しても同様のトピックが出てこないので、元々そういう仕様なのかなとも思いましたが、日本語のファイル名をひっかけたいとき、helm-do-grep時などみなさんどうされてるのかな、と気になりまして…。（migemoもありますが、grepでは効かないですし）

IMEはGoogle日本語入力です。試しにことえりに戻してみましたが、状況は変わりませんでした。

**Comment by syohex** [comment]
Linux環境では, 普通に日本語が入力できましたので, 根本的に日本語が入力できない
ということはなさそうです.

![helm-sample](https://cloud.githubusercontent.com/assets/554281/2901178/3961f16e-d5d1-11e3-8931-33d152b97bff.png)

Macについては後ほど調べてみます.

**Comment by shishi** [comment]
@takanopontaro さんと同じ環境で確かに日本語が入力できませんでした。ずっと使ってたのに日本語を検索することがなかったのか気づきませんでした…

**Comment by kawabata** [comment]
helm は（現時点の最新版は） overriding-terminal-local-map を
使っているので、elisp で書かれた input method は効かない
可能性があります。
（私のところでは使えませんでした）

一方、OS経由の日本語入力は（Emacsがイベントを横取りしなければ）
問題ないはずで、 MacOS 10.9 + Emacs 24.3.90 + MacPort Patch
（http://lists.gnu.org/archive/html/emacs-devel/2014-04/msg00176.html）
で、Google IME でhelm-recentf 等で日本語を入力でき、必要なファイルを
検索できています。

2014-05-07 20:03 GMT+09:00 Shigenobu Nishikawa notifications@github.com:

> @takanopontaro https://github.com/takanopontaroさんと同じ環境で確かに日本語が入力できませんでした。ずっと使ってたのに日本語を検索することがなかったのか気づきませんでした…
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/emacs-jp/issues/issues/17#issuecomment-42414056
> .

## 

---

川幡 太一 (KAWABATA, Taichi) E-mail: kawabata.taichi@gmail.com

**Comment by takanopontaro** [comment]
念のため再インストールしてみました。
…が、やはりダメでした。

``` shell
brew install emacs --srgb --japanese --cocoa --with-gnutls
```

バージョンを見るとVersion 24.3 (9.0)とあります。

一応リマップソフトのKeyRemap4MacBookを停止してみましたが変わらずです。
うーむ…

**Comment by takanopontaro** [comment]
コンソールから起動すると入力できますね。
GUIだとダメです。

**Comment by syohex** [comment]
確認してみたら, 確かにできませんでした.
しかし homebrewでなく自分で構築した, 開発版だと入力できました.

**Comment by syohex** [comment]
`--japanese`を外してインストールしてみたところ, 入力することができました.

```
% brew install emacs --srgb --cocoa --with-gnutls
```

**Comment by takanopontaro** [comment]
なるほど…
japaneseオプションはIMEインラインパッチを有効にするためと認識してるんですが、外しても大丈夫なんですかね…

**Comment by syohex** [comment]
`japanese`オプションがなくても日本語自体は入力できますので, 日本語入力さえ
できればよいというのであればなしでもいいかと思いますが, 各種説明の記事等を
見ているとあった方が良さそうです.

**Comment by znz** [comment]
`brew install emacs --cocoa --with-gnutls --srgb` でインストールしたものを使っていますが、端末の中と同じように emacs が IME の状態を扱わないというだけで、 ssh で入った先と同じようなものなので、特に不便は感じていません。
`distnoted` の暴走なども関わってくるので、両方試してみて、使いやすい方を使えば良いのではないでしょうか。

**Comment by takanopontaro** [comment]
みなさまアドバイスどうもありがとうございました。
--japaneseオプション無しで使ってみましたが、確かに日本語入力するには問題無いですね。
ただキーバインド絡みで不便なのでやはり元に戻しました。Helmへの日本語入力は基本ペーストで行こうと思います。ちょっと面倒ですが…
次のEmacsでは直ってるといいですね。
