### ISSUE TITLE
一部のサーバ にて erc-list が上手く動かない

### ISSUE THREAD

**Issue by Warashi** [emacs-jp/issues#18]
具体的には、IRCnet-JP にて erc-list が上手く動かないことを確認しています。
emacs -q してこちらの設定の影響はできるだけ排除した状態で確認しました。
erc-list-mode が enabled なのを確認後、/list しましたが、新しくバッファが開きません。
freenodeではちゃんと動作したので、サーバが正しくない応答を返している可能性もありますが……
これはerc-listのバグなのでしょうか、それともサーバ側の問題なのでしょうか。

Emacs の version は 24.3.1 で、 Arch Linux 上で動かしています
/list すると、サーバからのメッセージで
-irc.media.kyoto-u.ac.jp- Usage of /list for listing all channels is deprecated. Please use "/squery alis help" instead.
と表示されます。

**Comment by syohex** [comment]
IRCのことはよくわかっていませんが, サーバ側の問題ではないでしょうか ?
問題といっても `/list`が使えないというのであって, バグの類ではありません.

```
/quote squery list :list
```

詳しいことはわかっていませんが, 上記のようにするとチャネル情報が(少し)取れる
ようです. オプションを渡して数を調整できるそうですが, 詳しいことはわかりませんでした.
この方法ではバッファは開きませんでした.

**Comment by kawabata** [comment]
見当違いのことを言っているかもしれませんが、
ERCは、iso-2022-jp でエンコードされたチャンネル名を扱えないので、
日本語環境では使えないと思っています。

iso-2022-jp に対応した Emacs 用のIRCとして、rieceを使っています。

2014-08-27 22:41 GMT+09:00 Syohei YOSHIDA notifications@github.com:

> IRCのことはよくわかっていませんが, サーバ側の問題ではないでしょうか ?
> 問題といっても /listが使えないというのであって, バグの類ではありません.
> 
> /quote squery list :list
> 
> 詳しいことはわかっていませんが, 上記のようにするとチャネル情報が(少し)取れる
> ようです. オプションを渡して数を調整できるそうですが, 詳しいことはわかりませんでした.
> この方法ではバッファは開きませんでした.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/emacs-jp/issues/issues/18#issuecomment-53573511.

## 

---

川幡 太一 (KAWABATA, Taichi) E-mail: kawabata.taichi@gmail.com

**Comment by Warashi** [comment]
ありがとうございます。
とりあえず、erc-listの利用は諦めようと思います。

ERCが iso-2022-jp のチャンネル名を扱えないとのことですが、
erc-server-coding-systemに(iso-2022-jp . iso-2022-jp) を渡してやれば使えると思います。
とりあえずそれでjoinしたりできているので。
erc-listが動かないのはもしかしたらそれのせいかもしれませんが。
