### ISSUE TITLE
auto-install-from-urlの代替手段

### ISSUE THREAD

**Issue by murasesyuka** [emacs-jp/issues#19]
emacs packageの管理を遅ればせながら、auto-install.el + package.elからcaskに移行しました。
で、一点だけ気になる点としてauto-install-from-url相当の機能がcaskに無いところです。

cask本家は、「url指定は入れないよ」みたいな感じで機能追加されそうにもありません。

大体はelpa/melpaにありますし、最近はgit/githubで管理されているので、現状困っているというわけではないですが、皆さんはどうなさっていますか？

**Comment by syohex** [comment]
私の場合, そのような機能が必要になるのは mozc.elぐらいですが, それは手動で
インストールしています. めったにアップデートされることもないので, 一度
インストールすれば十分なので自動化するに至っていません.

任意の場所にあるパッケージをインストールしたいのであれば,
Caskではなく el-getを使うのが現状ベストでしょうか. 自分でレシピが書けるし,
インストール前後に行うコマンドも指定できるので, 任意のパッケージをインストール
することができます.

Caskでなんとかするのであれば, githubに mirrorを作る, (他の人にも需要があるなら)
MELPAに登録する等でしょうか.

**Comment by niku** [comment]
僕も @syohex さんと同じで，そういったファイルのみ手動でインストールしてます．

**Comment by murasesyuka** [comment]
あれ、思ったより手動使われているんですね。

代替手段は、el-getのレシピなのかなと何となく思ってましたが、たしかに手動でチャッチャと入れたほうが手っ取り早いですかね。

まあ過去資産もありますしauto-install等からの完全移行も、もうちょっとだけ時間が掛かるって事でしょうか。

**Comment by syohex** [comment]
LocalElpaというものがあるようですね.

http://www.emacswiki.org/emacs/LocalElpaArchive

**Comment by syohex** [comment]
ただ `Cask`だと任意のリポジトリというのは無理っぽいですね.

http://cask.readthedocs.org/en/latest/guide/dsl.html#el.function.source

**Comment by tarao** [comment]
僕はel-get派なのですが、たしかにレシピをいちいち書くのは(ちょっと試すだけのときなど特に)面倒なので、自分でラッパーを書いてレシピ書かなくても使えるようにしてます: [bundle-el](https://github.com/tarao/bundle-el)

``` elisp
(bundle pit
  :type http :url "https://gist.github.com/raw/4468816/pit.el"
  (autoload 'pit/get "pit")
  (autoload 'pit/set "pit"))
```

みたいに、その場でレシピ相当の部分(`:type`と`:url`のところ)を書けるだけでなく、インストールされているときに実行すべき設定も書けます(`autoload`のところ)。（あと設定部分はバイトコンパイルされます。)

**Comment by murasesyuka** [comment]
@syohex ドキュメントありがとうです。readthedocsに上げられているんですね。
@tarao サンプルどうもです。el-get使うときにパクらせてもらいます。

cask本家のissue https://github.com/cask/cask/issues/223 見てたら、なんかemacswikiのmirror使えとの回答が！？
githubにemacswikiのミラー https://github.com/emacsmirror とかあったんですね＞＜

**Comment by murasesyuka** [comment]
いろいろな知見が得られましたのでクローズします。
ありがとうございました。
