### ISSUE TITLE
Emacs24.3でibusが高負荷になってしまいます。

### ISSUE THREAD

**Issue by ghost** [emacs-jp/issues#2]
Emacs24.3でibusが高負荷になり、Emacsの操作が困難（終了も難しいくらい）になってしまいます。
このような現象が発生するのは僕だけでしょうか。
また、解決方法に心当たりがある方がいれば教えて下さい。

色々試してみた結果、popwin.elを利用している際に発生するような気がします。
Emacs24.2では発生しません。

僕の環境はUbuntu12.04をWindows7のVirtual Boxで利用しています。
また、popwinのバージョンは0.6です。

**Comment by syohex** [comment]
その現象は私も発生しています。原因はわかっていませんが、popwin.elは私も使っています。
ibus関連なので日本語入力関係の mozc.elあたりかと思っていたのですが、詳しい調査を
行わず、現状は 24.2を利用しています。

popwinを外して私も試してみます。

**Comment by m2ym** [comment]
```
(setq popwin:close-popup-window-timer-interval 0.05)
```

にするとどうですか？

**Comment by m2ym** [comment]
24.3特有のバグで`timer-list`にゾンビタイマーが溜まり続けます。本件と関係なく早めに対処バージョンリリースすべきですね。

**Comment by ghost** [comment]
@syohex @m2ym ありがとうございます。

```
(setq popwin:close-popup-window-timer-interval 0.05)
```

にしてみたところ、ibusが高負荷になり、操作が出来なくなると言ったことは発生しなくなりました。
ただ、popwin.elに関係なくibusのcpu使用率が上昇（操作が出来なくなるほどではありません）していました。

**Comment by tkf** [comment]
deferred や flyspell/flymake を多用していると遅くなる気がしたんですが、発生条件が良くわからず悩んでいました。 timer まわりだと考えれば納得です。

@m2ym Emacsのバグトラッカーには既に登録されていますか? ちょっと探しましたが見つけられませんでした。

**Comment by syohex** [comment]
@m2ym ありがとうございます。それだと何がきっかけで問題になるかわからないので、
次のバージョンが待たれますね。

**Comment by m2ym** [comment]
@tkf http://lists.gnu.org/archive/html/emacs-devel/2013-01/msg00445.html

よく見たら返信ついてました…

**Comment by kiwanami** [comment]
このスレッドは自分も気にしてましたが、途中からなんとなく話がずれていったような気がします。
タイマーで起動されたエラーを捕まえるようにした修正が関係有りそうで、結局まだ未解決という感じでしょうか。

**Comment by tkf** [comment]
@m2ym ありがとうございます。パッと見てみましたが、まともな返信は最初のひとつだけっぽくて実質スルーですねこれ。。。MLよりバグトラッカーのほうが後々修正される可能性があって良いんじゃないかと思うんですがどうでしょう。ただ、Emacsのバグトラッカーってまともに活用されてるか謎ですが。。。

@kiwanami 別の人がタイマー関連でエラー出るんだけど、って言った話に流されただけで、関連性は同時期に起こった以外に無い気がします。ぱっと見なので何か見逃しているかもしれませんけど。

**Comment by syohex** [comment]
`timer_check`関する修正だと以下ぐらいしか該当するものがなさそうですが、
まだ推測の域を全然出ていないので、何とも言えないですね。

http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=8559ff9c6ecf0e0b905fb293a8ddedd3b0ab896c

**Comment by m2ym** [comment]
ひとまずバグ回避のためpopwin 0.6.2をリリースしておきました。

**Comment by m2ym** [comment]
emacs-develに返信したので、しばらく様子見で。

**Comment by syohex** [comment]
:+1:

**Comment by syohex** [comment]
http://comments.gmane.org/gmane.emacs.devel/165276

年末までには 24.4リリースのため freezeされるそうなんですが、
この問題って解決されたのでしょうか ?

解決されていないなら, つついておきたいです.

**Comment by shibayu36** [comment]
このissueよく分かっていないのですが、mac os xとかでも同様の問題があるのでしょうか？たまに入力が固まり、以下の様なエラーが出ることがありました。

```
popwin:close-popup-window-timer: error: (error Variable binding depth exceeds max-specpdl-size)
```

**Comment by syohex** [comment]
@shibayu36 OS関係なくあるはずです. 上述のように `popwin:close-popup-window-timer-interval`を
変えてみるのはいかがでしょうか ?

**Comment by shibayu36** [comment]
@syohex この部分、最新のpopwinではデフォルトで0.05が指定されているように思ったのですが、自分で指定すべきなのでしょうか?

**Comment by syohex** [comment]
@shibayu36 大きめの値にすると良さそうに思えます.

https://twitter.com/akisute3/statuses/342946097225936896

**Comment by shibayu36** [comment]
@syohex なるほど、試してみます。ありがとうございます

**Comment by syohex** [comment]
昨日の段階での git repositoryのものを使ったらバグが再現しなくなっています.
以下の評価を繰り返しても, timer-listにゾンビが溜まらないようになっています.
(念の為確認したところ, 24.3では溜まる)

```
    (setq my-timer
          (run-with-timer
           nil 0.1
           (lambda ()
             (when my-timer
               (cancel-timer my-timer)
               (setq my-timer nil)
               (sit-for 0.3)))))
```

**Comment by kiwanami** [comment]
ほんとうですね。うちのLinux上の Emacs 24.3 だと、ばんばん溜まってます。
GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.4.4)

**Comment by syohex** [comment]
m2ymさんの方でも問題がなくなっていることが確認できたので closeします.
現状リポジトリのものでしか, 解決できませんが, Emacs 24.4向けのフリーズが
来月だそうなので, 24.4ではおそらく修正が取り込まれているものと思います.

24.4の Release candidateで問題が見られる等ありましたら, reopenすることと
します.
