### ISSUE TITLE
run-hooks について（バグ？）

### ISSUE THREAD

**Issue by Warashi** [emacs-jp/issues#20]
こんにちは。

run-hooks というか、気付いたのは run-hook-with-args-until-success を使ってる時だったんですが。

``` elisp
(defun t () (message "t"))
(setq my-hook (list t))
(run-hooks 'my-hook)
```

とかしても、 関数 t が実行されないようです。
以下のコードだと実行されます。

``` elisp
(defun t () (message "t"))
(run-hooks 't)
```

これって仕様なのでしょうか。

すいません、書き忘れていましたが、当方の環境は
Mac OS X Yosemite
Cocoa Emacs 24.4.1
です。

**Comment by Warashi** [comment]
add-hook あたりに原因？があるようです。
どうやら、buffer-local な variable にするときに (list t) を set しているようです。
そのせいで、結果としてできた hook に t が残ってしまうみたいなので、エラー回避のために run-hooks ではリストの中の t はスキップするようになっているのだと思われます。

以下、試してみたコードです。

``` elisp
(defvar my-hook)
(add-hook 'my-hook 'my-func nil t)
(print my-hook)

結果
(my-func t)
```

**Comment by syohex** [comment]
そもそも `t`という名前を使うこと自体がおかしいのではないでしょうか ?
Emacs Lisp(Common Lisp)等では, `t`は既に定義済みのシンボルなので,
それと同名の関数を作るという自体問題があるように思えます.

``` lisp
(defun foo () (message "@@ foo"))
(setq my-hook (list 'foo))
(run-hooks 'my-hook)
;; @@ fooが表示される
```

上記のように `t`以外だと(`a`でも), 期待通り動きます.

あと一番初めに示された例ですが, 下記と同じ意味になり,
`hook`に関数が指定できていないものと思います.

``` lisp
(defvar hoge t)
(defun hoge () (message "@@ hoge"))
(setq my-hook (list hoge))
(run-hooks 'my-hook)
;; @@ hogeは表示されない.
```

**Comment by Warashi** [comment]
おっと、例が適切でなかったのはこちらの落ち度です、すいません。

はい、そうですね。`t`という名前を使うのは適切ではないでしょう。
もともとこれに気付いたのは、`emacs -Q` で起動した状態で `M-x eshell` した後に `*eshell* buffer` にて `M-x describe-variable RET eshell-parse-argument-hook` した所、リストの途中に t が入っていたことから調べてみた結果です。関数呼び出し自体はできたので、run-hooks 関係では使えないのはなぜだろうかと思いまして。ちょっと気になったので詳しい人はいないだろうかとissueを立ててみた次第です。

自己解決したのに issue を close していなかったのはすいません、忘れていました。
