### ISSUE TITLE
C-gのキーバインドが効かない

### ISSUE THREAD

**Issue by rysk-t** [emacs-jp/issues#21]
初めまして，こんにちは．

先日 OSX Yosemite でEmacs を使用していたところ，いつの間にかC-gのキーバインドが全く働かないという状態になってしまいました，
quitが効かないという事では無いらしく，他のキーにkeyboard-quitを割り当てるとquit出来ます．
また，

""
  (global-set-key (kbd "C-g") 'helm-bookmarks)
""

のようにしてみても，C-gでhelm-bookmarksを起動することができません．
- 環境
  - Mac OSX 10.10.1 Yosemite
  - GNU Emacs 24.3.1 (x86_64-apple-darwin, NS apple-appkit-1038.36) of 2013-03-13 on bob.porkrind.org
  - GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-10-21 on builder10-9.porkrind.org

**Comment by rysk-t** [comment]
自己解決しました．ReadCubeというアプリが Ctrl-g を使用する設定になっていた，というオチでした...申し訳ありません．

**Comment by syohex** [comment]
> いつの間にかC-gのキーバインドが全く働かないという状態になってしまいました

確認なのですが, この「いつの間にか」というのは, 起動後しばらく経ったら, という意味でしょうか ?
(それとも Yosemiteにしたらそのようになってしまっていたという意味合いでしょうか ?)

これは拡張なし(`/Applications/Emacs.app/Contents/MacOS/Emacs -Q`)でも再現する
問題でしょうか ?

また Emacsのインストール方法を教えていただけないでしょうか(`homebrew`, `macports`等).

**Comment by syohex** [comment]
すいません, リロードせず, コメントを書いてしまいました.
