### ISSUE TITLE
(keybord-quit)をC-qなど他のキーに割り当てると正常動作してくれない

### ISSUE THREAD

**Issue by keicy** [emacs-jp/issues#22]
初めまして,こんにちは.

最近emacsを始め,デフォルトでC-gに割り当てられている(keyboard-quit)関数を
C-qに割り当て直したのですが,正常に動作してくれません.

具体的には、例えばM-x と打ってミニバッファ入力待ち状態にしたのちに
C-qを押すと,ミニバッファに「quit」と表示されるのですが,
その後またミニバッファ入力待ち状態になってしまいます.

上記例をデフォルトのC-g押下で行うと、押下後には元々といたバッファ(M-xを押下したバッファ)
に戻ってくれるので,キー割り当てをC-qに変更した際に挙動がおかしくなってしまっていると考えています.

割り当ての変更は,~/.emacs.d/init.el内に
(global-set-key (kbd "C-q") 'keyboard-quit)
と記述して行なっています.

C-qのキー割り当てで(keyboard-quit)関数を正常動作
させることは可能でしょうか？
なにかヒントになる情報などがありましたら,ご教授ください.

なお,動作環境は以下です.
## emacsはターミナル内ではなく、個別のウィンドウで起動して使っています。

OS: Debian 7.7
emacs: 24.3.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.4.2)

どうぞ,よろしくお願いいたします.

**Comment by keicy** [comment]
すみません,記述法が良くなかったようで文字の表示がおかしくなってしまいました.
文字が大きくなってしまった箇所は,特に強調の意図はありません,ご容赦下さい.

**Comment by syohex** [comment]
minibufferのキーマップでは, `C-g`は keyboard-quitではなく `abort-recursive-edit`に
マップされているためです. 以下のように設定するとうまくいかないでしょうか ?

``` lisp
(define-key minibuffer-local-map (kbd "C-q") 'abort-recursive-edit)
;; (define-key minibuffer-local-map (kbd "C-q") (kbd "C-g")) もしくはこちら
(global-set-key (kbd "C-q") 'keyboard-quit)
```

**Comment by keicy** [comment]
syohexさん,ご教授,ありがとうございます!
上記設定で、意図した通りの挙動になりました.
minibufferにも ローカルキーマップがあったということですね,勉強になりました.

では,このissueはクローズさせていただきます.
