### ISSUE TITLE
view-read-onlyがtだとvc-next-action時にバッファが切り替わっちゃう

### ISSUE THREAD

**Issue by hirose31** [emacs-jp/issues#23]
1. `touch /tmp/foo; ci -t-blah -u /tmp/foo`
2. `emacs -q /tmp/foo`
3. `M-x set-variable`
   - view-read-only t
4. `M-x vc-next-action`

でバッファが foo から他の (*scratch* とか) に移動しちゃうんですが、自分の環境だけでしょうか？（view-read-onlyがnilならfooのまま）
- GNU Emacs 24.3.1 (x86_64-Ubuntu-linux-gnu, X toolkit, Xaw scroll bars)

**Comment by lurdan** [comment]
手元では、同様の操作をするとミニバッファに
Checking out /tmp/foo...done
と表示されてバッファには特に変化ない感じです (24.4.1 /Debian sid)

**Comment by syohex** [comment]
3回, `vc-next-action`を実行したとき, Emacs 24.3, Emacs 24.4はそんな挙動になりました.
一方開発版はそのような挙動にはなりませんでした.

#### Emacs 24.3, Emacs 24.4

![vc-next-action](https://cloud.githubusercontent.com/assets/554281/6387585/bb6aae20-bdd0-11e4-8750-feefdb8bb64f.gif)

#### Emacs development version

![vc-next-action-devel](https://cloud.githubusercontent.com/assets/554281/6387586/bedf5eb6-bdd0-11e4-8c13-cfa208fccfec.gif)

`vc-next-action`を全く使ったことがないのですが, どのような挙動になるのが
期待通りなのでしょうか ?

**Comment by hirose31** [comment]
書き込み不可状態（co -uしてる状態）でvc-next-actionすると書き込み可能（co -l）になるんですが、そのときにバッファは変わらないで欲しい（これからそのバッファを編集するので）感じっす。

**Comment by syohex** [comment]
`vc-resynch-window`を下記で再定義してみて試していただけないでしょうか ?

``` el
(require 'vc)
(require 'vc-dispatcher)
(defun vc-resynch-window (file &optional keep noquery reset-vc-info)
  (and (string= buffer-file-name file)
       (if keep
           (progn
             (when (file-exists-p file)
               (when reset-vc-info
                 (vc-file-clearprops file))
               (vc-revert-buffer-internal t noquery)
               (and view-read-only
                    (progn
                      (if (file-writable-p file)
                          (progn
                            (and view-mode
                                 (let ((view-old-buffer-read-only nil))
                                   (view-mode-exit t)))) ;; 第一引数を指定し, quit-windowしないようにする
                        (and (not view-mode)
                             (not (eq (get major-mode 'mode-class) 'special))
                             (progn
                               (view-mode-enter))))))
               ;; FIXME: Why use a hook?  Why pass it buffer-file-name?
               (run-hook-with-args 'vc-mode-line-hook buffer-file-name)))
     (kill-buffer (current-buffer)))))
```

**Comment by hirose31** [comment]
@syohex ばっちりでした！！！！！！！！！！！！！！！（ｽｺﾞｲ

**Comment by syohex** [comment]
挙動を変更するパラメータがあるわけではないので, このように無理やり上書きすること
でしか回避できないと思います.
