### ISSUE TITLE
evil-textobj-multiblockという拡張を書いたので添削して欲しいです

### ISSUE THREAD

**Issue by supermomonga** [emacs-jp/issues#25]
README.mdに

> elisp書いたんで, 読んでみて欲しい.

というのも可とあったので投稿します。

vimのtextobj-multiblockをEvilに移植してみました。
コード自体は短いものの、Emacs Lisp初心者のためコードに自信がないので、添削して頂けると嬉しいです。

https://github.com/supermomonga/evil-textobj-multiblock/tree/4434d22100770fa64a82b96a6622fd217e8cfb1b

参考:
- [textobj-multiblock つくった](textobj-multiblock つくった)
- [osyo-manga/vim-textobj-multiblock](https://github.com/osyo-manga/vim-textobj-multiblock)

**Comment by supermomonga** [comment]
個人的には`ignore-errors`に厳しみを感じています。

**Comment by yuutayamada** [comment]
こんにちは、 evil 今年から使い出したのでそのパッケージにはお世話になりそうです。

少し気になったところをいくつか書かせていただきます。

``` lisp
(require 'cl)
```

の部分ですが、`eval-when-compile`でくくらないとバイトコンパイル時にwarningが出ると思います。

``` lisp
(eval-when-compile (require 'cl))
```

あとおせっかいですが、もしMELPAなどにパッケージを登録するのであれば

``` lisp
;; Package-Requires: ((emacs "24.3") (cl-lib "0.5"))
```

のような依存パッケージや、Emacsのバージョンなどを書く必要があります。(この場合はevilパッケージですね)

FYIとして、`ignore-errors`についてですが、`condition-case`を利用するというのもありかもしれません。

``` lisp
(condition-case err
    (message "このなかでerrorがあったら、下のerror節で処理される")
  (error (message (format "errorがあったらerrをmessageバッファへ: %s" err))))
```

最後にこれは個人的な意見なので人によっては、違うというかもしれませんがdefine-keyでの登録はユーザーが側で選択できるようにしたほうがいいと思いました。
僕もevilを使っているのですが、 evil-outer-text-objects-mapもしくはinner-mapはすべてのmajor-mode共通で利用するので

``` lisp
(define-key evil-outer-text-objects-map (kbd "b")
  (lambda ()
    (interactive)
    (cl-case major-mode ; major-modeによって関数を切り分ける
      (lisp-mode lispに特化したtext-obj関数)
      (org-mode  org-modeに特化したtext-obj関数))))
```

のようなことをしていた(もしくはしたい)場合、(require 'evil-textobj-multiblock)した段階でユーザーが設定していたキーマップが変更されてしまう可能性があります。(autoloadの場合もありますね)

**Comment by yuutayamada** [comment]
あっすいません、define-keyでの登録で問題になるのは主にautoloadの場合ですね。(requireで最初からinit.elから起動時に読み込むなら、ファイルの読み込み順序変えればいいだけでした)

**Comment by tarao** [comment]
[SHOULD]

Vim版の仕様に従うと、範囲の候補が複数あった場合に`evil-textobj-multiblock-blocks`に定義されている順に優先したいように思えます。最後に`sort`しているところで`a`と`b`が等しかったら定義順も比べるとよさそう? `count`があるときにも大丈夫なのかとか細かいところはよくわかりませんが。

> ```
> " 次のような場合は g:textobj_multiblock_blocks に
> " 先に設定されている括弧が優先される
> ```
> 
>  http://d.hatena.ne.jp/osyo-manga/20130329/1364569153

**Comment by tarao** [comment]
[MAY]

`cl-remove-if`よりも`loop`マクロで書いた方が見通しがいい(`mapcar`の中身と`null`で取り除くのをいっぺんに書ける)かもしれません。

**Comment by tarao** [comment]
[MAY]

`(length selections)`を計算すると1回リストをナメる分もったいないので、空でもとにかく`sort`して、`car`ではなく`car-safe`で結果を取得し、その結果が`nil`の場合に`error`にするとよさそうです。

**Comment by tarao** [comment]
[COMMENT]

`evil-select-paren`に正規表現を渡すことで扱いたい括弧をぜんぶ一気に渡すというのも考えましたが、そうすると括弧の種類の対応がとれなかったり、`evil-textobj-multiblock-blocks`の優先順位を扱うのが難しくなったりするので、やはり1つずつ文字を渡して成功するかどうか確かめていくしかなさそうですね。なので`ignore-errors`を使うこと自体は本質的には仕方ない気がします。

**Comment by tarao** [comment]
僕からは以上です。

**Comment by syohex** [comment]
既に出ているような感じですが.
- `(require 'cl)`でなく `(require 'cl-lib)`. `remove-if`ではなく, `cl-remove-if`を使っているため.
- `cl-remove-if`より `cl-loop`の方が見栄え的にはよさそう

``` lisp
(cl-remove-if
 'null
 (mapcar (lambda (paren)
           (let ((open (nth 0 paren)) (close (nth 1 paren)))
             (ignore-errors (evil-select-paren open close beg end type count inclusive))))
         parentheses))
```

``` lisp
(cl-loop for (open close) in parentheses
         for selected = (ignore-errors
                          (evil-select-paren open close beg end type count inclusive))
         when selected
         collect selected)
```
- `length < 1`というのは空リストなので, `null`の方が良い(@taraoさんの方式でも良いと思います)

**Comment by tarao** [comment]
> `a`と`b`が等しかったら定義順も比べるとよさそう?

これですが、そもそも`selections`が`evil-textobj-multiblock-blocks`の定義順を保存したものになっているので、`sort`が安定ソートである限り意図通りになりそうですね(そして`sort`は実際に安定ソートです)。失礼しました。

**Comment by supermomonga** [comment]
@yuutayamada @tarao @syohex 添削ありがとうございます！参考にして、書きなおしてみます。特に`loop`はかなり強力そうですね。なんとなく避けてしまっていました…。

> Vim版の仕様に従うと、範囲の候補が複数あった場合にevil-textobj-multiblock-blocksに定義されている順に優先したいように思えます。

Vim版の仕様を正確に再現するには、現在のように単純な位置比較でなく、ネストの深さの判定も含めて厳密にチェックするロジックを組む必要がありそうですね。次の課題としてみます。

**Comment by supermomonga** [comment]
https://github.com/supermomonga/evil-textobj-multiblock/blob/7190405f729448ab22ed40c77e61a3b30bca58dd/evil-textobj-multiblock.el

添削を便りに無事コードを改善することができたと思います。添削して下さった @yuutayamada さん、 @takaishi さん、 @syohex さん、ありがとうございました。
