### ISSUE TITLE
direx.elでfaceが反映されない

### ISSUE THREAD

**Issue by takanopontaro** [emacs-jp/issues#26]
お世話になっております。
最近direx.elを使い始めましてお気に入りになっているのですが、1点気になることが。

僕の環境だとなぜかfaceが一切反映されず全部デフォルト色のままなのです。
diredのfaceになるのが正解だと思うのですが…

M-x customizeでdiredのfaceをいじってもダメで、しかしdiredバッファはちゃんと色付いてます。

ググってもこれといったものが出てこないので、ちょっと検討つかず…
どなたかお心当たりありましたらと思い、書かせていただきました。

▼環境
Mac OSX 10.10
railwaycat/emacs-mac-port最新版をhomebrewで入れ、GUIで使っとります。

▼M-x emacs-version
GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0, Carbon Version 157 AppKit 1348.17)

**Comment by syohex** [comment]
具体的にどの faceを変更して反映されないのでしょうか ? 手元で試したところ, `dired-directory`を変更すると direxの方でも反映されることが確認できました. 少し見た感じだと変更できそうな faceは `dired-directory`と, `dired-ignored`だけのように思えます

faceの確認は, 調べたい位置までカーソルを持っていき, `M-: (face-at-point)`をすればできます.

![orig](https://cloud.githubusercontent.com/assets/554281/9894204/1ed3ace4-5c5c-11e5-9bc9-b0743dc23e2a.png)

`M-: (set-face-foreground 'dired-directory "orange")`を適用後

![after](https://cloud.githubusercontent.com/assets/554281/9894205/2349da46-5c5c-11e5-9459-8a34cf2159f7.png)

**Comment by takanopontaro** [comment]
以下のようにすべてのfaceが反映されない状態で、(face-at-point)でnilが返ります。

![screenshot](https://cloud.githubusercontent.com/assets/2234824/9894790/eddac47c-5c62-11e5-9841-db074fb94cb5.jpg)

が、もしやと思いdirex.elのみの状態で試すと色付けされました。
いろいろ調べた結果、以下のコードが原因でした。

(global-whitespace-mode 1)

これを取ると上手くいきます。
ただ、whitespaceは表示させておきたいので、設定で振り分けようと思います。

最初に試してからIssueをたてるべきでした。お騒がせしました。

**Comment by syohex** [comment]
問題が再現することを確認しました.

特定のモードだけ global-whitespace-modeを無視する設定は下記のような感じで行えます. direxでも whitespace-modeを使いたいというのでは無理ですが, direxでは不要ということであればこれで解決できるかと思います.

```
(setq whitespace-global-modes '(not direx:direx-mode))
```

**Comment by takanopontaro** [comment]
そういう書き方があるんですね。知りませんでした。
どうもありがとうございます！

**Comment by syohex** [comment]
それで問題がなければ closeしていただければと思います.
