### ISSUE TITLE
Emacs on Windows の IMEのバグについて

### ISSUE THREAD

**Issue by fenril058** [emacs-jp/issues#29]
GNUのサイトで配布されているEmacs 24.3, 24.4, 24.5のWindows版のバイナリでは、日本語IMEによるインライン表示ができないという問題がありますが、原因は、

「emacs が WM_IME_STARTCOMPOSITION メッセージを自前で処理しつつメッセージをシステムに返さない (DefWindowProc に渡さない) という動作をすること」

であり、

「WM_IME_STARTCOMPOSITION ハンドラ内部で break; するのではなく、goto dflt; すればいい」

という解決策の提案が既に24.3の頃にされていた(https://productforums.google.com/forum/#!topic/ime-ja/tgXztpe84ok) ことを知りました(http://cha.la.coocan.jp/doc/NTEmacsIMEpatch.html 経由で)。

この修正をEmacs本家に取り入れられないものでしょうか。

**Comment by syohex** [comment]
なんとも言えないですが, 可能性があるとすれば本家 MLで熱心にアピールするぐらいですかね. MacOSX向けのパッチを書いている千葉大学の山本さんという方はその功績が認められたのか, 今まで独立していたパッチが本家に取り込まれようとしているようです.

過去一年ほどの MLを調べたところ, Windows向けの IMEについての議論を行ったものはないようですので, まずは提案してみるところからでしょうか. (英語圏の人には理解しづらい問題なので大変なことだと思いますが...)

**Comment by lurdan** [comment]
パッチ自体も、結構長い期間にわたって様々な人の手が入ってるようなので、Copyright assignment の手続きが障壁になっているのかもしれませんね……

**Comment by fujii** [comment]
以前、その goto dflt するパッチは一旦はコミットされたのですが、
ファイル選択ダイアログで問題が発生してリバートされました。
https://debbugs.gnu.org/db/11/11732.html
私はその問題を再現できずにそのままになってしまいました。

**Comment by fenril058** [comment]
皆様、早速のお返事ありがとうございます。
ということは @fujii さんが示してくださったファイル選択ダイアログ問題を解決しないとならないということですね。これはなかなか苦しそうです。
