### ISSUE TITLE
org-modeのtableでセル結合したい

### ISSUE THREAD

**Issue by murasesyuka** [emacs-jp/issues#3]
色々調べてみて、デフォルトではセル結合の記法が無さそうなのは解りました。

　ただrowspan, colspan辺りは、table使用していて普通に欲しい機能だと思います。
ってか私は欲しいです。

　無さそうなので、現状は縦結合は以下のように空白でごまかしています。

```
|      | foo |
| name | bar |
|      | baz |
```

　table.elでtableを変換する方法もあるようですが、
行数が倍に増えて可読性的に嬉しくないなって感じです。

なにか良い方法、手法、拡張等はないでしょうか？

**Comment by takaishi** [comment]
これは僕も欲しい機能ですね．
代替案があれば知りたいです

**Comment by takaxp** [comment]
何度か本家MLでも出ていますが，やはり table.el が現状の解のようです．
縦方向のセルの連結に該当するのは，セル内の自動改行なのですが，
横方向のセルの連結は難しいようです．
現状ではセルの結合という見た目よりも，セルの値を利用した演算が重視
されているようですね．結合した後のTBLFMでの演算式とか
すごく複雑になりそうです．

技術的にはオーバーレイでセル2つ分を常に上書き表示するといったアプローチがあるのかもしれません．
elisp初心者なので適当なコメントですみません．

**Comment by murasesyuka** [comment]
@takaishi ですよね。欲しいです。
@takaxp さん、ありがとうございます。

　やっぱりtable.elということになるのですね。
食わず嫌いであまり試せてなかったので少し触ってみました。

  emacs 24.2 
  org-mode 7.9.3e

> 縦方向のセルの連結に該当するのは，セル内の自動改行なのですが，
> 横方向のセルの連結は難しいようです．

　table.elで変換したtableで、
C-jで縦方向（セル内改行）
「|」を削除で横方向の結合が出来るようです。

※何処かtable.elのtable操作の情報ないでしょうか。ググッても余り引っかからない

　上記方法で結合したtable.elのtableを、htmlにexportしてみると
縦方向は改行<br>が挿入され、横方向はcolspanが指定されていたので
変換結果は期待したものです。

　ただorg-mode tableとtable.el tableの相互変換が不可逆なので
table.el tableで体裁整えて、org-mode tableに戻すとか出来なさそうなのが残念です。

　table.el tableを使用するなら体裁を整える最後に利用、って感じでしょうかね？

**Comment by murasesyuka** [comment]
org-modeのtableでは、
「セル結合は現状は出来ない」との結論が得られたので
closeします。

回答ありがとうございました。
