### ISSUE TITLE
GNU Emacs 24.5.1 で `*.gpg` を開こうとすると `error in process filter: Wrong type argument: listp, t`

### ISSUE THREAD

**Issue by znz** [emacs-jp/issues#30]
Emacs 24.5.1 の EasyPG で `*.gpg` を開こうとすると `error in process filter: Wrong type argument: listp, t` になるので原因を調べてみたところ、`~/.emacs.d/init.el` で http://www.bookshelf.jp/cgi-bin/goto.cgi?file=meadow&node=delete%20history に書いてあるような以下の hook を設定していたことが原因だとわかりました。

必須な機能というわけでもないので、コメントアウトして使わなくすれば解決したのですが、どうすればエラーなく使えるようになるでしょうか?

``` elisp
;; history から重複したのを消す
(eval-when-compile (require 'cl))
(defun minibuffer-delete-duplicate ()
  (let (list)
    (dolist (elt (symbol-value minibuffer-history-variable))
      (unless (member elt list)
        (push elt list)))
    (set minibuffer-history-variable (nreverse list))))
(add-hook 'minibuffer-setup-hook 'minibuffer-delete-duplicate)
```

**Comment by syohex** [comment]
再現するさせるための最小限の設定, 手順を示していただけないでしょうか ?

上記の設定と, 以下の設定で `*.gpg`ファイルを開いても(`emacs-24.5 -Q`で起動)特に問題が発生しませんでした.

```
(require 'epa-file)
(epa-file-enable)
```

**Comment by znz** [comment]
パスフレーズをきいてくるはずがエラーになって入力できないという問題で、Vagrant で用意したクリーンな Ubuntu 15.10 の環境でもこれだけで再現するので、`gpg-agent` が有効になっている環境だと `(setenv "GPG_AGENT_INFO" nil)` などで無効にする必要があるのかもしれません。

**Comment by znz** [comment]
最小限の環境作成用の Vagrantfile を用意してみました。
https://gist.github.com/znz/647fdd9c2f6c76f84b12c03ea4feab85

`vagrant up` して `vagrant ssh` で入った後、 `emacs hoge.txt.gpg` で再現します。

**Comment by syohex** [comment]
vagrantでやってみましたが, 問題が起きないですね.

**Comment by lurdan** [comment]
Windows 環境の vagrant で、現象の再現自体はされました (その先の切り分けはしてませんが、一応……
- vagrant 1.8.1
- Virtualbox 5.0.16

**Comment by fujii** [comment]
minibuffer-history-variable が t なので、
チェックを入れると回避できます。

``` lisp
(defun minibuffer-delete-duplicate ()
  (when (listp minibuffer-history-variable)
    (let (list)
      (dolist (elt (symbol-value minibuffer-history-variable))
    (unless (member elt list)
      (push elt list)))
      (set minibuffer-history-variable (nreverse list)))))
```

なぜ minibuffer-history-variable が t になるかはわかりませんでした。

**Comment by fujii** [comment]
read-passwd の中で t を指定してました。しかもコメント付きで。

``` lisp
              (read-string
               (if noninteractive
                   (format "%s[INPUT WILL NOT BE HIDDEN!] " prompt) ; bug#17839
                 prompt)
               nil t default)) ; t = "no history"
```

**Comment by znz** [comment]
こちらでもチェックを入れることで回避できました。
原因調査までありがとうございます。
toggle-debug-on-error をしておいても関係ないエラーで止まってしまって、原因が探し切れていなかったので助かりました。
