### ISSUE TITLE
Emacs25.3(64bit) on Windows でいくつかのユニコード絵文字が化ける

### ISSUE THREAD

**Issue by fenril058** [emacs-jp/issues#32]
sky-color-clock.el をつかって初めて気が付いたのですが、Winodwsの64bit版Emacs 25.3では🌑🌓といった絵文字がうまく表示されませんでした。一方32bit版の方ではきちんと表示されました。この挙動は、IMEパッチを当てたものも、公式で配布されているバイナリでもまったく同じでした。

だからといってとくに日常的使用において、支障はないのですが一応気が付いたのでここに書き込みました。気持ち悪くはあるので直せるなら直したい思いはあるのですが。

**Comment by lurdan** [comment]
私も 64bit NTEmacs で、下記の文字の表示ができなくて困ってました。

https://github.com/abo-abo/oremacs/blob/github/modes/ora-ivy.el#L17

24.x では表示できて、25.x では表示できなかったのですが、26.pretest で試すと表示できたので、今のところは次のリリースを待てばいいかなぁ……と様子を見てる感じです
