### ISSUE TITLE
macOS の Emacs で絵文字が表示できない

### ISSUE THREAD

**Issue by znz** [emacs-jp/issues#33]
https://qiita.com/tadsan/items/a67b28dd02bf819f3f4e によると最近の Emacs だと何も設定しなくても表示できると書いてあるのですが、 `brew install emacs --with-cocoa` で入れた Emacs.app でも `brew cask install emacs` で入れた Emacs.app でも表示できません。
どうすれば表示できるようになるのでしょうか?
(主に github からの通知メールを wanderlust で表示すると絵文字が見えないというのに困っているので、他の回避策があるというのでも嬉しいのですが。iTerm2 の中なら表示できるので、絵文字がありそうな時は `emacsclient -t` で見るという方法もなくはないですが。)

**Comment by zonuexe** [comment]
これは記事の書きかたが若干ミスリーティングなのですが、

> Emacs 25.1では、[デフォルトでいい感じの設定](https://github.com/emacs-mirror/emacs/commit/8d9e5bab41aa1995d801112b8413b514e59f033e)と[macOSでのカラー絵文字サポートの廃止](https://github.com/emacs-mirror/emacs/blob/2c2b0cd07c143e33af9f7237ef4819c28764a90f/etc/NEWS#L2610-L2617)が入ってるんで、アップデートするひとはもはやemoji-fontset.elをインストールする必要はないですよ ヾ(〃＞＜)ﾉﾞ

https://github.com/emacs-mirror/emacs/commit/8d9e5bab41aa1995d801112b8413b514e59f033e のように[Symbola](http://users.teilar.gr/~g1951d/)がないと絵文字の表示はできません。 ~~この文章を書いた奴はわかりにくいと感じなかったのか~~

**Comment by zonuexe** [comment]
この追記が意味するところは「`emoji-fontset`パッケージを入れる必要がない」であって、「絵文字フォント(Symbola)をインストールしなくてよい」ではなかったようですね。カラー絵文字が現役だったときの`Apple Color Emoji`の`Segoe UI Emoji`は表示できなくなってしまったので……。

**Comment by znz** [comment]
Symbola をダウンロードして `~/Library/Fonts/` に入れたら(白黒ですが)表示できるようになりました。
ありがとうございます☺️
