### ISSUE TITLE
keyboard-quit の beep を差し替えたい

### ISSUE THREAD

**Issue by lurdan** [emacs-jp/issues#4]
具体的には、C-g を連打していった時、最後は beep のかわりに close-other-windows として動いて欲しいのですが、実現できるものでしょうか？
(keyboard-quit をそのままコピペして my- 関数としていじるのは最後の手段)

**Comment by kiwanami** [comment]
「最後」の定義が気になります。

**Comment by zonuexe** [comment]
僕はこれと逆に `ESC` を連打したときに `C-g` と同様の動作(`close-other-windows`されない)にしたいと思って `C-h k C-g` で `C-g` のときに呼ばれる函数がわからなかったのでしばらく放置してたのですが、この issue をヒントにやってみたら、僕のやりたかったことは実現できました。

``` init.el
(global-set-key (kbd "M-ESC ESC") 'keyboard-quit)
```

ってことはつまりつまり、 `ESC` 連打と同じことを `C-g` に割り当てれば良いので…

``` init.el
(global-set-key (kbd "C-g") 'keyboard-escape-quit)
```

これで @lurdan さんの望み通りの挙動になる気がしますヾ(〃＞＜)ﾉﾞ☆

**Comment by lurdan** [comment]
すみません、@zonuexe さんの方法で解決していたのですが、閉じるのをすっかり忘れてました……
