### ISSUE TITLE
header-line-formatが非 nilである際の mozcの問題

### ISSUE THREAD

**Issue by syohex** [emacs-jp/issues#6]
header-line-formatが非 nilであるとき mozc-candidate-styleが overlayであるとうまくいかない.
header-line-formatが nilだと左側のように正常に表示されるが、header-line-formatが非 nil(空文字含む)で
あると右側のように予測候補が適切に表示されない.

![mozc-overlay](https://f.cloud.github.com/assets/554281/899114/898579f0-fb33-11e2-9d01-bfcfc826796b.png)

このスレッドと関連している問題と考えられる. company-modeでは対応できている
ようなので、それを参考に修正できないかを検討する.

http://lists.gnu.org/archive/html/emacs-devel/2013-05/msg00145.html

この問題は Emacs 24以降で発生する。23では発生しない.
以下の設定で変換候補を出せば再現できる.

``` lisp
(require 'mozc)
(setq default-input-method "japanese-mozc")
(setq mozc-candidate-style 'overlay)
(setq header-line-format "")
```

**Comment by syohex** [comment]
本家に報告

https://code.google.com/p/mozc/issues/detail?id=196&thanks=196&ts=1376382692

**Comment by syohex** [comment]
https://code.google.com/p/mozc/issues/detail?id=196

修正されたようです. 以前とは若干表示が変わったように思えますが
(header-lineなしでも同様), 横に伸びてしまうという現象は起こらなくなっています.

![mozc](https://f.cloud.github.com/assets/554281/1867126/49261c6a-7848-11e3-9686-17d415ef0034.png)

ping @hirose31

**Comment by hirose31** [comment]
@syohex おおおありがとうございます！！！

**Comment by tam17aki** [comment]
overlayではなく、popupを用いて表示させる以下のmozc-popupというパッケージも便利です。
https://github.com/d5884/mozc-popup
