### ISSUE TITLE
設定済Emacs for Windows

### ISSUE THREAD

**Issue by katoken-0215** [emacs-jp/issues#7]
設定済Meadowのように、All-in-oneなEmacs installerがあると便利じゃないでしょうか。

http://www.bookshelf.jp/soft/meadow_8.html

**Comment by syohex** [comment]
使ったことがないのでよくわかっていないのですが, [gnupack](http://sourceforge.jp/projects/gnupack/)が
Meadowには近いのではないかと思います. あと Emacs 24以降であれば, package.elが
あるので, それを使ってパッケージをインストールする方法を早い段階で
知ってもらえるというのがベストかなと思います. package.elは HTTPの
通信ができれば使えるので, 会社等ネットワークの制限が厳しい環境でも
導入は用意です(HTTP Proxyを通せば使える).

インストーラではありませんが, 便利なパッケージとその設定をあらかじめ用意するという
プロダクトはいくつかあります. Windowsではあんまり試験されていなそうですが,
機種依存がそこまであると思えないし, git等のセットアップさえなんとかなれば
導入できるのではないかと思います。
- [prelude](https://github.com/bbatsov/prelude)
- [emacs24-starter-kit](https://github.com/eschulte/emacs24-starter-kit)
- [oh-my-emacs](https://github.com/xiaohanyu/oh-my-emacs)
- [emacs-live](https://github.com/overtone/emacs-live)
- [cabbage](https://github.com/senny/cabbage)

**Comment by Shougo** [comment]
そうですね。私的にもgnupackはお勧めです。というより、gnupackを使わずにWindows環境でEmacsを使おうとすると軽く地獄を見ると思います。

**Comment by katoken-0215** [comment]
個人的事情で設定済Meadowユーザを改宗させるために、Emacs24 + オススメ.el というのが欲しいんですよ。
gnupack は全部面倒をみてくれるので楽なんですけど、素のCygwinがあるとややこしくなるので、なるべく避けたいんです。

ちょっと頑張って作ってみます。
モノができるか諦めるかしたらクローズで良いでしょうか?

**Comment by syohex** [comment]
> ちょっと頑張って作ってみます。
> モノができるか諦めるかしたらクローズで良いでしょうか?

そうですね.

もう少し調べてみましたが, 同様のものは見つかりませんでした.

おすすめとして何を選ぶかにもよりますが, あるバージョンを固定して
持っておくというのはメンテナンスのコストが高いと思いますので,
付与するパッケージは最低限にして, package.elを使うようにした方が
良いと思います.

**Comment by ongaeshi** [comment]
まだ作り途中ですが、こういうのを作っています。

[ongaeshi/emacs-brave](https://github.com/ongaeshi/emacs-brave)

特徴としては、
- Emacs初心者が難しい設定をせずに比較的新しいEmacsの機能を使うことが出来る
- 他の人のEmacs環境を~/.emacs.d/ を汚さずに試すことが出来る

みたいなのを目指しています。
README.mdにも書いてありますがTest Runが出来るので良かったらお試し下さい。

※ Emacs熟練者の皆さんの~/.emacs.d/を気軽に試すことが出来るようになったら楽しいなぁ・・とか妄想しています。

**Comment by ghost** [comment]
@ongaeshi いいですね。
いま海外との仕事でHPが底ついてしまって、
なかなかWindows版ビルドとインストーラ作るどころではないのですが、
いつかそれができたら是非、同梱してインストール時に入れるかどうか選択するようにさせてください！

つことはgit入れないとアップデートできないのか。 う〜ん。 (ToT)

**Comment by ghost** [comment]
Openしたままで申し訳ないので、一度Closedにします。しばらく作る時間が取れる確証もありませんし。
もしWindows版作れたらそのときにまたOpenします。

@ongaeshi @syohex @Shougo 
情報ありがとうございました。
また再開するときには必ず参考にさせていただきます。

**Comment by ghost** [comment]
閉じ方がわかりません ><

@syohex 
貴殿のコメント右上にownerと出ているので、 Closedにできるかどうか試していただけないでしょうか。

**Comment by syohex** [comment]
閉じました

**Comment by katoken-0215** [comment]
@syohex 

ありがとうございます。
会社用のアカウントで書き込んでいたのでClosedにできなかったことに今気づきました。
お手数をお掛けしました。

**Comment by Shougo** [comment]
最近gnupackは更新されていないので、そろそろalternativeなものが必要そうですね……。
