### ISSUE TITLE
emacs-snapshotでは削除されているad-safe-fsetの置き替えについて

### ISSUE THREAD

**Issue by niku** [emacs-jp/issues#9]
travis-ci で同じコードを異なるEmacsで単体テストをしています．

emacs24 だと[テストをパス](https://travis-ci.org/niku/quick-toggle/jobs/14733787)するのに
emacs-snapshot だと[テストに失敗](https://travis-ci.org/niku/quick-toggle/jobs/14733788)しました．

エラーの内容は `(void-function ad-safe-fset)` をググったところ
http://lists.gnu.org/archive/html/emacs-diffs/2012-11/msg01170.html
で `(ad-safe-fset): Remove.` されており，単純に `fset` で置き替えられているようです．

ライブラリとして使っている el-mock でこの関数 `ad-safe-fset` を呼び出しているのですが
ここについても `fset` で置き替えるだけでよいのでしょうか．

識者のご意見をおまちしております．

**Comment by syohex** [comment]
mockする関数に adviceがなければ `fset`で置き換えても何も問題ないと思います.
Emacs 24.3までは, `fset`だと adviceは引き継がれるようですが, 24.4以降は,
明示的に指定する必要があるようです.

しいて問題があるとすれば, adviceすることで mockの内容が変わってしまう
ようなものでしょうか. mockの内容はバッファへ 10文字挿入, adviceで 1文字
削除みたいなことがあると, 単純に `fset`に置き換えると Emacs 24.3より前
では失敗すると思います.  なんで置き換えるとすれば以下のような感じ
でしょうか. (`ad-activate-on-top-level`は 24.4では既に削除されています.)

``` lisp
(let ((ad-activate-on-top-level nil))
  (fset foo bar))
```

**Comment by niku** [comment]
ありがとうございます．
advaice については，考えておかないといけないですね．
